# SQL SERVER
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databasename=rgbled
    username: sa
    password: sa
  jpa:
    database: sql-server
    hibernate:
      ddl-auto: update
    show-sql: false
  
server:
  port: 8083